/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Background = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: BackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type BackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionImageTextBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionImageTextBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionImageTextBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type FeatureCardImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "featureCard.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionFeatureCardsBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionFeatureCardsBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionFeatureCardsBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionFeatureCards.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionCardGridBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionCardGridBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionCardGridBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionCardGrid.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionStatsBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionStatsBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionStatsBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionStats.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionArchShowcaseBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionArchShowcaseBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionArchShowcaseBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionArchShowcase.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionGalleryBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionGalleryBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionGalleryBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionGallery.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionAccordionBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionAccordionBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionAccordionBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionAccordion.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionMediaFeatureBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionMediaFeatureBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionMediaFeatureBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionMediaFeature.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionStepsBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionStepsBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionStepsBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionSteps.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionDynamicListBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionDynamicListBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionDynamicListBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionDynamicList.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionLogosBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionLogosBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionLogosBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionLogos.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionQuoteBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionQuoteBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionQuoteBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionQuote.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionCtaBandBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionCtaBandBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionCtaBandBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionCtaBand.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SectionFaqListBackground = {
  tone?: 'default' | 'warm' | 'chapel' | 'chapelDeep';
  image?: SectionFaqListBackgroundImage;
  videoUrl?: string;
  overlay?: number;
  padding?: 'compact' | 'normal' | 'spacious';
};

export type SectionFaqListBackgroundImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "sectionFaqList.background.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type CourseReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'course';
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  role?: string;
  city?: string;
  courseCompleted?: CourseReference;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  featured?: boolean;
  displayOrder?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TeachingAreaReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'teachingArea';
};

export type FacultyMember = {
  _id: string;
  _type: 'facultyMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  honorific?: string;
  slug?: Slug;
  title?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  teachingAreas?: Array<
    {
      _key: string;
    } & TeachingAreaReference
  >;
  specializations?: Array<string>;
  ordination?: string;
  denomination?: 'PC(USA)' | 'ECO' | 'EPC' | 'Other';
  degrees?: Array<{
    degree?: string;
    field?: string;
    institution?: string;
    year?: string;
    _type: 'degree';
    _key: string;
  }>;
  affiliations?: Array<{
    role?: string;
    organization?: string;
    _type: 'affiliation';
    _key: string;
  }>;
  yearsTeaching?: string;
  publications?: Array<{
    title?: string;
    publisher?: string;
    year?: string;
    url?: string;
    _type: 'publication';
    _key: string;
  }>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h3';
    listItem?: 'bullet';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  humanLine?: string;
  email?: string;
  displayOrder?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type FacultyMemberReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'facultyMember';
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type TermReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'term';
};

export type PricingTierReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'pricingTier';
};

export type Course = {
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  level?: 'Intro' | 'Foundational' | 'Advanced';
  teachingAreas?: Array<
    {
      _key: string;
    } & TeachingAreaReference
  >;
  instructors?: Array<
    {
      _key: string;
    } & FacultyMemberReference
  >;
  format?: 'In person' | 'Hybrid';
  location?: string;
  whoFor?: Array<string>;
  sessionOutline?: Array<{
    title?: string;
    focus?: string;
    _type: 'courseSession';
    _key: string;
  }>;
  syllabusFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  offerings?: Array<{
    term?: TermReference;
    schedule?: string;
    sessions?: number;
    seatsNote?: string;
    status?: 'open' | 'waitlist' | 'closed';
    _type: 'courseOffering';
    _key: string;
  }>;
  priceTier?: PricingTierReference;
  priceNote?: string;
  featured?: boolean;
  startHere?: boolean;
  displayOrder?: number;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type PricingTier = {
  _id: string;
  _type: 'pricingTier';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  amount?: number;
  unit?: 'per course' | 'per track' | 'per term';
  summary?: string;
  includes?: Array<string>;
  isAudit?: boolean;
  featured?: boolean;
  displayOrder?: number;
};

export type Term = {
  _id: string;
  _type: 'term';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  startDate?: string;
  endDate?: string;
  registrationOpens?: string;
  registrationDeadline?: string;
  status?: 'upcoming' | 'open' | 'inSession' | 'closed';
  note?: string;
};

export type TeachingArea = {
  _id: string;
  _type: 'teachingArea';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  displayOrder?: number;
};

export type Announcement = {
  _id: string;
  _type: 'announcement';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  message?: string;
  style?: 'info' | 'special' | 'urgent';
  link?: {
    label?: string;
    url?: string;
  };
  startDate?: string;
  endDate?: string;
  enabled?: boolean;
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eventType?: 'recurring' | 'oneTime';
  category?:
    | 'Info session'
    | 'Open lecture'
    | 'Workshop'
    | 'Webinar'
    | 'Term start'
    | 'Application deadline'
    | 'Community'
    | 'Other';
  audience?: 'Everyone' | 'Lay leaders' | 'Newcomers' | 'Prospective students' | 'Clergy';
  scheduleLabel?: string;
  start?: string;
  end?: string;
  allDay?: boolean;
  location?: string;
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h3';
    listItem?: 'bullet';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  registrationUrl?: string;
  registrationLabel?: string;
  cost?: string;
  contactName?: string;
  contactEmail?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  featured?: boolean;
  featuredOnHome?: boolean;
};

export type FaqCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqCategory';
};

export type FaqItem = {
  _id: string;
  _type: 'faqItem';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h4';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  category?:
    | 'Visiting'
    | 'Worship'
    | 'Kids & Family'
    | 'Getting Involved'
    | 'Giving'
    | 'Weddings & Space'
    | 'Food Ministry';
  categoryRef?: FaqCategoryReference;
  displayOrder?: number;
};

export type AccessibilityPage = {
  _id: string;
  _type: 'accessibilityPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type PrivacyPage = {
  _id: string;
  _type: 'privacyPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type NotFoundPage = {
  _id: string;
  _type: 'notFoundPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  mission?: string;
  funder?: string;
  email?: string;
  pastorEmail?: string;
  phone?: string;
  officeHours?: string;
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  addressLine?: string;
  cityStateZip?: string;
  geoLat?: number;
  geoLng?: number;
  navItems?: Array<
    | {
        label?: string;
        href?: string;
        _type: 'navLink';
        _key: string;
      }
    | {
        label?: string;
        links?: Array<{
          label?: string;
          href?: string;
          _type: 'navSubLink';
          _key: string;
        }>;
        _type: 'navGroup';
        _key: string;
      }
  >;
  footerColumns?: Array<{
    title?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _type: 'footerLink';
      _key: string;
    }>;
    _type: 'footerColumn';
    _key: string;
  }>;
  worshipService?: {
    time?: string;
    day?: string;
    startTime24?: string;
    endTime24?: string;
  };
  watchUrl?: string;
  giveUrl?: string;
  appUrl?: string;
  directoryUrl?: string;
  registrationBaseUrl?: string;
  prayerUrl?: string;
  socialInstagram?: string;
  socialFacebook?: string;
  socialYoutube?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
};

export type SectionFaqList = {
  _type: 'sectionFaqList';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  categoryRef?: FaqCategoryReference;
  categoryString?: string;
  limit?: number;
  ctaLabel?: string;
  ctaUrl?: string;
  background?: SectionFaqListBackground;
};

export type FaqCategory = {
  _id: string;
  _type: 'faqCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  displayOrder?: number;
};

export type SectionArchShowcase = {
  _type: 'sectionArchShowcase';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  mediaType?: 'slideshow' | 'video';
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  videoUrl?: string;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  background?: SectionArchShowcaseBackground;
};

export type SectionDynamicList = {
  _type: 'sectionDynamicList';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  source?: 'featuredCourses' | 'upcomingEvents' | 'faculty';
  count?: number;
  background?: SectionDynamicListBackground;
};

export type SectionMediaFeature = {
  _type: 'sectionMediaFeature';
  eyebrow?: string;
  heading?: string;
  body?: string;
  mediaSide?: 'left' | 'right';
  videoUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  ctaLabel?: string;
  ctaUrl?: string;
  background?: SectionMediaFeatureBackground;
};

export type SectionLogos = {
  _type: 'sectionLogos';
  heading?: string;
  intro?: string;
  grayscale?: boolean;
  items?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    url?: string;
    _type: 'image';
    _key: string;
  }>;
  background?: SectionLogosBackground;
};

export type SectionSteps = {
  _type: 'sectionSteps';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  steps?: Array<{
    title?: string;
    body?: string;
    _type: 'step';
    _key: string;
  }>;
  background?: SectionStepsBackground;
};

export type SectionGallery = {
  _type: 'sectionGallery';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  columns?: '2' | '3' | '4';
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
  background?: SectionGalleryBackground;
};

export type SectionAccordion = {
  _type: 'sectionAccordion';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _type: 'qa';
    _key: string;
  }>;
  background?: SectionAccordionBackground;
};

export type SectionStats = {
  _type: 'sectionStats';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  columns?: '2' | '3' | '4';
  items?: Array<{
    value?: string;
    label?: string;
    note?: string;
    _type: 'stat';
    _key: string;
  }>;
  background?: SectionStatsBackground;
};

export type SectionFeatureCards = {
  _type: 'sectionFeatureCards';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  columns?: '2' | '3' | '4';
  arched?: boolean;
  cards?: Array<{
    image?: FeatureCardImage;
    eyebrow?: string;
    title?: string;
    body?: string;
    badge?: string;
    ctaLabel?: string;
    ctaUrl?: string;
    _type: 'featureCard';
    _key: string;
  }>;
  background?: SectionFeatureCardsBackground;
};

export type FormReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'form';
};

export type SectionForm = {
  _type: 'sectionForm';
  heading?: string;
  intro?: string;
  form?: FormReference;
};

export type SectionCtaBand = {
  _type: 'sectionCtaBand';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  background?: SectionCtaBandBackground;
};

export type SectionQuote = {
  _type: 'sectionQuote';
  quote?: string;
  attribution?: string;
  background?: SectionQuoteBackground;
};

export type SectionCardGrid = {
  _type: 'sectionCardGrid';
  eyebrow?: string;
  heading?: string;
  subhead?: string;
  columns?: '2' | '3' | '4';
  cards?: Array<{
    title?: string;
    body?: string;
    link?: string;
    _type: 'card';
    _key: string;
  }>;
  background?: SectionCardGridBackground;
};

export type SectionImageText = {
  _type: 'sectionImageText';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  imageSide?: 'left' | 'right';
  arched?: boolean;
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h3' | 'h4' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  ctaLabel?: string;
  ctaUrl?: string;
  background?: SectionImageTextBackground;
};

export type SectionRichText = {
  _type: 'sectionRichText';
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h3' | 'h4' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  align?: 'left' | 'center';
  background?: Background;
};

export type Embed = {
  _type: 'embed';
  title?: string;
  mode?: 'url' | 'html';
  url?: string;
  html?: string;
  aspect?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'homePage';
};

export type AboutPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'aboutPage';
};

export type FaqPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'faqPage';
};

export type ContactPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'contactPage';
};

export type EventsPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'eventsPage';
};

export type CoursesPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'coursesPage';
};

export type FacultyPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'facultyPage';
};

export type PricingPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'pricingPage';
};

export type GetStartedPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'getStartedPage';
};

export type ForYouPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'forYouPage';
};

export type ResourcesPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'resourcesPage';
};

export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type CtaBlock = {
  _type: 'ctaBlock';
  label?: string;
  linkType?: 'internal' | 'external' | 'email' | 'phone';
  internalLink?:
    | HomePageReference
    | AboutPageReference
    | FaqPageReference
    | ContactPageReference
    | EventsPageReference
    | CoursesPageReference
    | FacultyPageReference
    | PricingPageReference
    | GetStartedPageReference
    | ForYouPageReference
    | ResourcesPageReference
    | PageReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  sections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type ResourcesPage = {
  _id: string;
  _type: 'resourcesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCta?: CtaBlock;
  listIntro?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
};

export type ForYouPage = {
  _id: string;
  _type: 'forYouPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCta?: CtaBlock;
  personasIntro?: string;
  personas?: Array<{
    label?: string;
    promise?: string;
    cta?: CtaBlock;
    _type: 'persona';
    _key: string;
  }>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
};

export type GetStartedPage = {
  _id: string;
  _type: 'getStartedPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCta?: CtaBlock;
  requestForm?: FormReference;
  calendlyUrl?: string;
  requestEyebrow?: string;
  requestHeadline?: string;
  requestBody?: string;
  calendlyEyebrow?: string;
  calendlyHeadline?: string;
  calendlyBody?: string;
  visitClassBody?: string;
  syllabusBody?: string;
  stepsHeadline?: string;
  steps?: Array<{
    title?: string;
    body?: string;
    _type: 'getStartedStep';
    _key: string;
  }>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
};

export type PricingPage = {
  _id: string;
  _type: 'pricingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCta?: CtaBlock;
  pricingIntro?: string;
  scholarshipEyebrow?: string;
  scholarshipHeadline?: string;
  scholarshipBody?: string;
  footnote?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
};

export type FacultyPage = {
  _id: string;
  _type: 'facultyPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCta?: CtaBlock;
  directoryIntro?: string;
  aggregateTrustLine?: string;
  emptyState?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
};

export type CoursesPage = {
  _id: string;
  _type: 'coursesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCta?: CtaBlock;
  catalogIntro?: string;
  startHereEyebrow?: string;
  startHereHeadline?: string;
  emptyState?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
};

export type EventsPage = {
  _id: string;
  _type: 'eventsPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  specialEyebrow?: string;
  specialHeadline?: string;
  upcomingEyebrow?: string;
  upcomingHeadline?: string;
  upcomingEmpty?: string;
  rhythmsEyebrow?: string;
  rhythmsHeadline?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  detailFinalCtaEyebrow?: string;
  detailFinalCtaHeadline?: string;
  detailFinalCtaSubhead?: string;
  detailFinalCta?: CtaBlock;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  formIntroNote?: string;
  contactForm?: FormReference;
  whatToExpectEyebrow?: string;
  note?: string;
  whoToReachLabel?: string;
  contactReasons?: Array<{
    label?: string;
    value?: string;
    href?: string;
    _type: 'contactReason';
    _key: string;
  }>;
  gettingHereLabel?: string;
  gettingHereBody?: string;
  formSectionHeadline?: string;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type Form = {
  _id: string;
  _type: 'form';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heading?: string;
  intro?: string;
  mode?: 'native' | 'embed';
  fields?: Array<{
    label?: string;
    name?: string;
    type?: 'text' | 'email' | 'tel' | 'textarea' | 'select' | 'checkbox' | 'date';
    required?: boolean;
    placeholder?: string;
    helpText?: string;
    options?: Array<string>;
    width?: 'full' | 'half';
    _type: 'formField';
    _key: string;
  }>;
  submitLabel?: string;
  successMessage?: string;
  consentNote?: string;
  provider?: {
    service?: 'web3forms' | 'formspree' | 'email';
    accessKey?: string;
    notifyEmail?: string;
  };
  embedUrl?: string;
  embedHtml?: string;
};

export type FaqPage = {
  _id: string;
  _type: 'faqPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroKeyword?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  categoryOrder?: Array<string>;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  secondaryCta?: CtaBlock;
  note?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
};

export type AboutPage = {
  _id: string;
  _type: 'aboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  missionEyebrow?: string;
  missionStatement?: string;
  missionBody?: string;
  believeEyebrow?: string;
  believeHeadline?: string;
  beliefs?: Array<{
    title?: string;
    body?: string;
    _type: 'belief';
    _key: string;
  }>;
  believeFootnote?: string;
  teachEyebrow?: string;
  teachHeadline?: string;
  teachBody?: string;
  whyEyebrow?: string;
  whyHeadline?: string;
  whyBody?: string;
  facultyBandEyebrow?: string;
  facultyBandHeadline?: string;
  facultyBandCtaLabel?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  heroPrimaryLabel?: string;
  heroSecondaryLabel?: string;
  nextCohortLabel?: string;
  wayfinding?: Array<{
    title?: string;
    body?: string;
    href?: string;
    _type: 'wayfindingStep';
    _key: string;
  }>;
  startHereEyebrow?: string;
  startHereHeadline?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    count?: boolean;
    _type: 'stat';
    _key: string;
  }>;
  tickerTopics?: Array<string>;
  coursesEyebrow?: string;
  coursesHeadline?: string;
  coursesLinkLabel?: string;
  facultyEyebrow?: string;
  facultyHeadline?: string;
  facultyLinkLabel?: string;
  testimonialsEyebrow?: string;
  testimonialsHeadline?: string;
  flexibleSections?: Array<
    | ({
        _key: string;
      } & SectionRichText)
    | ({
        _key: string;
      } & SectionImageText)
    | ({
        _key: string;
      } & SectionFeatureCards)
    | ({
        _key: string;
      } & SectionCardGrid)
    | ({
        _key: string;
      } & SectionStats)
    | ({
        _key: string;
      } & SectionArchShowcase)
    | ({
        _key: string;
      } & SectionGallery)
    | ({
        _key: string;
      } & SectionAccordion)
    | ({
        _key: string;
      } & SectionMediaFeature)
    | ({
        _key: string;
      } & SectionSteps)
    | ({
        _key: string;
      } & SectionDynamicList)
    | ({
        _key: string;
      } & SectionLogos)
    | ({
        _key: string;
      } & SectionQuote)
    | ({
        _key: string;
      } & SectionCtaBand)
    | ({
        _key: string;
      } & SectionForm)
    | ({
        _key: string;
      } & SectionFaqList)
    | ({
        _key: string;
      } & Embed)
  >;
  finalCtaEyebrow?: string;
  finalCtaHeadline?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Background
  | SanityImageAssetReference
  | BackgroundImage
  | SectionImageTextBackground
  | SectionImageTextBackgroundImage
  | FeatureCardImage
  | SectionFeatureCardsBackground
  | SectionFeatureCardsBackgroundImage
  | SectionCardGridBackground
  | SectionCardGridBackgroundImage
  | SectionStatsBackground
  | SectionStatsBackgroundImage
  | SectionArchShowcaseBackground
  | SectionArchShowcaseBackgroundImage
  | SectionGalleryBackground
  | SectionGalleryBackgroundImage
  | SectionAccordionBackground
  | SectionAccordionBackgroundImage
  | SectionMediaFeatureBackground
  | SectionMediaFeatureBackgroundImage
  | SectionStepsBackground
  | SectionStepsBackgroundImage
  | SectionDynamicListBackground
  | SectionDynamicListBackgroundImage
  | SectionLogosBackground
  | SectionLogosBackgroundImage
  | SectionQuoteBackground
  | SectionQuoteBackgroundImage
  | SectionCtaBandBackground
  | SectionCtaBandBackgroundImage
  | SectionFaqListBackground
  | SectionFaqListBackgroundImage
  | CourseReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | TeachingAreaReference
  | FacultyMember
  | Slug
  | FacultyMemberReference
  | SanityFileAssetReference
  | TermReference
  | PricingTierReference
  | Course
  | PricingTier
  | Term
  | TeachingArea
  | Announcement
  | Event
  | FaqCategoryReference
  | FaqItem
  | AccessibilityPage
  | PrivacyPage
  | NotFoundPage
  | SiteSettings
  | SectionFaqList
  | FaqCategory
  | SectionArchShowcase
  | SectionDynamicList
  | SectionMediaFeature
  | SectionLogos
  | SectionSteps
  | SectionGallery
  | SectionAccordion
  | SectionStats
  | SectionFeatureCards
  | FormReference
  | SectionForm
  | SectionCtaBand
  | SectionQuote
  | SectionCardGrid
  | SectionImageText
  | SectionRichText
  | Embed
  | HomePageReference
  | AboutPageReference
  | FaqPageReference
  | ContactPageReference
  | EventsPageReference
  | CoursesPageReference
  | FacultyPageReference
  | PricingPageReference
  | GetStartedPageReference
  | ForYouPageReference
  | ResourcesPageReference
  | PageReference
  | CtaBlock
  | Page
  | ResourcesPage
  | ForYouPage
  | GetStartedPage
  | PricingPage
  | FacultyPage
  | CoursesPage
  | EventsPage
  | ContactPage
  | Form
  | FaqPage
  | AboutPage
  | HomePage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
